// Detailed stack data — categorized with proficiency, years, descriptions.
// Levels: 5 = expert (daily, deep), 4 = strong (production), 3 = working (used in projects), 2 = familiar
window.STACK_DATA = {
  ru: {
    coreTitle: "Основной стек",
    coreSubtitle: "С чем работаю каждый день в продакшне",
    coreNote: "// 5 лет коммерческого опыта",
    levelLabels: { 5: "expert", 4: "strong", 3: "working", 2: "familiar" },
    yearsLabel: "лет",
    core: [
      { name: "Go (Golang)", years: 5, level: 5, note: "основной язык, идиоматичный код, generics, profiling" },
      { name: "PostgreSQL", years: 5, level: 5, note: "индексы, партиционирование, EXPLAIN, миграции" },
      { name: "Apache Kafka", years: 4, level: 4, note: "консьюмеры, idempotent producer, partitioning" },
      { name: "Docker / K8s", years: 5, level: 4, note: "compose, helm, deployment стратегии" },
      { name: "gRPC + REST", years: 5, level: 5, note: "protobuf, streaming, идемпотентность" },
    ],
    groups: [
      {
        id: "lang",
        title: "Языки программирования",
        kicker: "languages",
        desc: "Go — основной. Python для CV/скриптов. SQL — везде, где данные.",
        items: [
          { n: "Go", lvl: 5, role: "primary", years: 5 },
          { n: "Python", lvl: 3, role: "data / cv", years: 3 },
          { n: "SQL", lvl: 5, role: "queries / migrations", years: 5 },
          { n: "JavaScript", lvl: 3, role: "admin UIs", years: 2 },
          { n: "Bash", lvl: 3, role: "scripts / ops" },
        ],
      },
      {
        id: "db",
        title: "Базы данных",
        kicker: "data layer",
        desc: "Хранилище под нагрузку. PostgreSQL для OLTP, ClickHouse для аналитики, Redis для кэша и locks.",
        items: [
          { n: "PostgreSQL", lvl: 5, role: "primary OLTP", years: 5 },
          { n: "MySQL", lvl: 4, role: "fintech tx tables", years: 2 },
          { n: "ClickHouse", lvl: 4, role: "OLAP / events", years: 1 },
          { n: "Redis", lvl: 4, role: "cache / locks / queues" },
          { n: "Elasticsearch", lvl: 3, role: "full-text / logs" },
        ],
      },
      {
        id: "msg",
        title: "Брокеры сообщений",
        kicker: "messaging",
        desc: "Асинхронные интеграции, event-driven архитектура, межсервисные коммуникации.",
        items: [
          { n: "Apache Kafka", lvl: 4, role: "event bus", years: 4 },
          { n: "RabbitMQ", lvl: 3, role: "task queues" },
          { n: "gRPC", lvl: 5, role: "inter-service RPC", years: 5 },
          { n: "REST / HTTP", lvl: 5, role: "external APIs", years: 5 },
          { n: "Temporal", lvl: 4, role: "durable workflows" },
        ],
      },
      {
        id: "infra",
        title: "Инфраструктура и DevOps",
        kicker: "platform",
        desc: "CI/CD, контейнеризация, оркестрация. Самостоятельно поднимаю окружения и пайплайны.",
        items: [
          { n: "Docker", lvl: 5, role: "containers", years: 5 },
          { n: "Kubernetes", lvl: 4, role: "deployments / GitOps" },
          { n: "GitLab CI/CD", lvl: 4, role: "pipelines / auto-deploy" },
          { n: "Linux", lvl: 4, role: "ops / debugging" },
          { n: "Git", lvl: 5, role: "vcs" },
        ],
      },
      {
        id: "obs",
        title: "Наблюдаемость и тестирование",
        kicker: "observability",
        desc: "SLA в продакшене требует видимости. Метрики, логи, трейсы, тесты.",
        items: [
          { n: "Prometheus", lvl: 4, role: "metrics" },
          { n: "Grafana", lvl: 4, role: "dashboards" },
          { n: "zap (logger)", lvl: 4, role: "structured logs" },
          { n: "testify", lvl: 4, role: "unit / integration" },
          { n: "OpenTelemetry", lvl: 3, role: "tracing" },
        ],
      },
      {
        id: "ai",
        title: "AI / Computer Vision",
        kicker: "ai · cv",
        desc: "Применение AI-инструментов в разработке + production CV-модели на YOLO.",
        items: [
          { n: "YOLO", lvl: 3, role: "object detection" },
          { n: "Cursor", lvl: 4, role: "AI IDE" },
          { n: "Claude Code", lvl: 4, role: "AI pair-programming" },
          { n: "Memory Bank", lvl: 3, role: "context engineering" },
        ],
      },
    ],
  },
  en: {
    coreTitle: "Core stack",
    coreSubtitle: "What I work with every day in production",
    coreNote: "// 5 years of commercial experience",
    levelLabels: { 5: "expert", 4: "strong", 3: "working", 2: "familiar" },
    yearsLabel: "yrs",
    core: [
      { name: "Go (Golang)", years: 5, level: 5, note: "primary language, idiomatic code, generics, profiling" },
      { name: "PostgreSQL", years: 5, level: 5, note: "indexes, partitioning, EXPLAIN, migrations" },
      { name: "Apache Kafka", years: 4, level: 4, note: "consumers, idempotent producer, partitioning" },
      { name: "Docker / K8s", years: 5, level: 4, note: "compose, helm, deployment strategies" },
      { name: "gRPC + REST", years: 5, level: 5, note: "protobuf, streaming, idempotency" },
    ],
    groups: [
      {
        id: "lang",
        title: "Programming languages",
        kicker: "languages",
        desc: "Go is primary. Python for CV/scripts. SQL anywhere data lives.",
        items: [
          { n: "Go", lvl: 5, role: "primary", years: 5 },
          { n: "Python", lvl: 3, role: "data / cv", years: 3 },
          { n: "SQL", lvl: 5, role: "queries / migrations", years: 5 },
          { n: "JavaScript", lvl: 3, role: "admin UIs", years: 2 },
          { n: "Bash", lvl: 3, role: "scripts / ops" },
        ],
      },
      {
        id: "db",
        title: "Databases",
        kicker: "data layer",
        desc: "Storage under load. PostgreSQL for OLTP, ClickHouse for analytics, Redis for cache and locks.",
        items: [
          { n: "PostgreSQL", lvl: 5, role: "primary OLTP", years: 5 },
          { n: "MySQL", lvl: 4, role: "fintech tx tables", years: 2 },
          { n: "ClickHouse", lvl: 4, role: "OLAP / events", years: 1 },
          { n: "Redis", lvl: 4, role: "cache / locks / queues" },
          { n: "Elasticsearch", lvl: 3, role: "full-text / logs" },
        ],
      },
      {
        id: "msg",
        title: "Message brokers",
        kicker: "messaging",
        desc: "Async integrations, event-driven architecture, inter-service comms.",
        items: [
          { n: "Apache Kafka", lvl: 4, role: "event bus", years: 4 },
          { n: "RabbitMQ", lvl: 3, role: "task queues" },
          { n: "gRPC", lvl: 5, role: "inter-service RPC", years: 5 },
          { n: "REST / HTTP", lvl: 5, role: "external APIs", years: 5 },
          { n: "Temporal", lvl: 4, role: "durable workflows" },
        ],
      },
      {
        id: "infra",
        title: "Infrastructure & DevOps",
        kicker: "platform",
        desc: "CI/CD, containerization, orchestration. I bring up environments and pipelines myself.",
        items: [
          { n: "Docker", lvl: 5, role: "containers", years: 5 },
          { n: "Kubernetes", lvl: 4, role: "deployments / GitOps" },
          { n: "GitLab CI/CD", lvl: 4, role: "pipelines / auto-deploy" },
          { n: "Linux", lvl: 4, role: "ops / debugging" },
          { n: "Git", lvl: 5, role: "vcs" },
        ],
      },
      {
        id: "obs",
        title: "Observability & testing",
        kicker: "observability",
        desc: "Production SLA demands visibility. Metrics, logs, traces, tests.",
        items: [
          { n: "Prometheus", lvl: 4, role: "metrics" },
          { n: "Grafana", lvl: 4, role: "dashboards" },
          { n: "zap (logger)", lvl: 4, role: "structured logs" },
          { n: "testify", lvl: 4, role: "unit / integration" },
          { n: "OpenTelemetry", lvl: 3, role: "tracing" },
        ],
      },
      {
        id: "ai",
        title: "AI / Computer Vision",
        kicker: "ai · cv",
        desc: "AI tooling in everyday dev + production CV models on YOLO.",
        items: [
          { n: "YOLO", lvl: 3, role: "object detection" },
          { n: "Cursor", lvl: 4, role: "AI IDE" },
          { n: "Claude Code", lvl: 4, role: "AI pair-programming" },
          { n: "Memory Bank", lvl: 3, role: "context engineering" },
        ],
      },
    ],
  },
};
